### ISSUE TITLE
Training scripts

### ISSUE THREAD

**Issue by JayKarhade** [facebookresearch/PoseDiffusion#10]
Hi, 

Thank you so much for releasing the demo code for this interesting work!

I am wondering if you plan to release the training code for PoseDiffusion?

Thank you!

**Comment by jytime** [comment]
Hi @JayKarhade ,

I've uploaded a training code on the dev branch. It can provide you with an example of how to train the model.

Please note that this code has been refactored and is not exactly the same as our original training code. We haven't fully tested its performance yet. It's just released to share as an example, and very likely that the code will be updated quickly next week.

Best,
Jianyuan

**Comment by JayKarhade** [comment]
Thank you so much! Will make do with this for now. Looking forward to the updated code!

**Comment by jytime** [comment]
Hey @JayKarhade , the training script has been slightly updated in the dev branch. It should be able to reproduce the training result now.
