### ISSUE TITLE
Hloc based sampson error

### ISSUE THREAD

**Issue by fearless-pilgrim** [facebookresearch/PoseDiffusion#12]
Hello jianyuan~
    I noticed that you only utilize hloc in inference not for extra training. I have tried to adopt your code to solve the sparse view taken from codv1, but the matching results are so bad that may not be useful in the next refine step.
    So, I am wondering how you evaluate the matching results in the process, only referencing the Sampson error?
![0b01feca5208b2aa9f14da57c5f07d1a](https://github.com/facebookresearch/PoseDiffusion/assets/69374757/390924d0-ffd1-4878-87f1-cf4b40936fb6)

**Comment by jytime** [comment]
Hi Zhiwei,

I have to admit that I do not fully understand your question. Are you asking how to guarantee the accuracy of matching results is enough for geometry-guided sampling? In practice, the Sampson error as the approximation of the epipolar constraint equation can be a good enough indicator. You can use the "ground truth" camera poses and different matches to compute the Sampson error, to roughly measure the quality of extracted matches.

Btw, looking at the images you pasted here, it appears that the images you attached are not in their original resolution. Image resolution is a critical factor that can significantly influence the quality of hloc (or other methods') matches.

**Comment by fearless-pilgrim** [comment]
Thank you for your careful reply. As you mentioned, I was wondering whether the matching results are good enough to support the Sampson error-guided constraints. I followed your process and attempted to test it by computing the Sampson error.

By the way, I don't think the images were resized. The images are loaded from 'co3dv1,' which refers to your code. It's possible that the angle between them is too steep, making it challenging to obtain good matches.

![1d3536a34bf7d5205abe871f28962b5d](https://github.com/facebookresearch/PoseDiffusion/assets/69374757/2de9e450-3c9f-4c28-9193-4c4263115e91)

In the case of the image view angle not changing significantly, it appears that 'hloc' could produce convincing results.
