### ISSUE TITLE
Errors when running the demo

### ISSUE THREAD

**Issue by markinruc** [facebookresearch/PoseDiffusion#18]
Thanks for your great work!  
I met the error when running the demo.  I guess it may be a problem with the HLOC, but I don't know how to solve it.

The error message is shown in the image below.
![image](https://github.com/facebookresearch/PoseDiffusion/assets/72591695/80837db9-ed4b-42eb-ac74-3e154a817293)

I would greatly appreciate it if you could help me solve it！
Thank you!

**Comment by jytime** [comment]
Hi,

I think it is because Hloc cannot find any pairs in your specific folder, where you can say it "Found 0 pairs". Although it seems you are running on samples/apple, can you double check what's the value of `folder_path` in your work? Probably  there is not any image in your `folder_path`.
