### ISSUE TITLE
RealEstate10k annotation

### ISSUE THREAD

**Issue by yuyu0927** [facebookresearch/PoseDiffusion#19]
Hi Jianyuan,

If I wanna train model on RealEstate10k, how should I preprocess the annotations of it? Is that in the same way with Co3D V2 dataset?

**Comment by jytime** [comment]
Hi yu,

Overall it follows the same flow but please be really careful with the coordinate conversion. If I remember correctly, Re10k also uses the COLMAP coordinate. Therefore, you can follow the sample [here](https://github.com/facebookresearch/PoseDiffusion/issues/9#issuecomment-1671724043), and convert it from COLMAP coordinate to Pytorch3D one. Generally speaking, you need to permute/transpose the rotation matrix, and make the xy axis negative for both rotation and translation. You can refer to my code there. I would suggest to visualize the cameras to check all are good after finishing it.

Good luck.

**Comment by yuyu0927** [comment]
Hi Jianyuan,

最近在处理RealEstate10k的数据，从官方下载的数据集都是txt文件，包含每个视频的链接和frame的信息，然后我从github另一处找到一个下载该数据的repo，改了改然后设置成了下载720p的视频再获取frame。下一步就是进行coordinate转换，xy均取反（因为两个坐标系定义中xy方向相反），rotation matrix要转置（因为要和pytorch3D相适应），RealEstate10k中是不包含bbox和catergory信息的，将其参照co3d annotation的格式保存为jgz文件即可（没有的信息就忽略）。请问我这样的处理方式正确吗？

**Comment by jytime** [comment]
Hi Yu,

Yes it is correct. Please be careful that you should do rotation matrix transpose first, and then take the negative of xy.

**Comment by jytime** [comment]
And if you want to do GGS on Re10K, please notice that resolution is really important for small baseline images like Re10k. It is always good to keep Re10k images the original resolution when doing GGS.

**Comment by yuyu0927** [comment]
Thanks for your correction and advice! Actually I reversed the order in coordinate conversion. I will revise and visualize the corrected coordinate tomorrow. I understand that I should keep it in original resolution because it affects feature extraction in GGS. Btw, could you explain briefly why rotation matrix transpose should be done at first?

**Comment by jytime** [comment]
Hi @yuyu0927 , I just uploaded the dataset file for Re10K. I am going to train a new model on this version and check its performance.

**Comment by huntorochi** [comment]
@yuyu0927 
你好yuyu，请问下载该数据的repo是哪个呀，处理后的RealEstate10k的数据方向和colmap方向有什么区别呀。
R转置并且改变xy方向之后就是colmap的w2c吗？
如果可以能的话可以复制一下你的修正代码吗？

**Comment by huntorochi** [comment]
@jytime 
Hi Jytime, I want to learn more about the difference in direction between the Estate dataset and the colmap.
I found Yuyu, and you said we need to transpose the rotation matrix first and then take the negative of xy.
So after that, what matrix can we get? Is it the Colmap W2C matrix? 

`
posemat = extrinsics.reshape(3, 4).astype('float64')
R = posemat[:3,:3].T
t = posemat[:3,-1]
transform_matrix = np.array([[R[0, 0], R[0, 1], R[0, 2], t[0]],
                                         [R[1, 0], R[1, 1], R[1, 2], t[1]],
                                         [R[2, 0], R[2, 1], R[2, 2], t[2]],
                                         [0.0, 0.0, 0.0, 1.0]])
transform_matrix[:3, 0:2] *= -1 
`
(for colmap W2C matrix)
Does it correct?

**Comment by jytime** [comment]
Hi @huntorochi ,

We have a dataset file about how to convert re10k to pytorch3d. 

https://github.com/facebookresearch/PoseDiffusion/blob/main/pose_diffusion/datasets/re10k.py


Basically here are two coordinates: OpenCV (i.e., colmap cam_from_world/world_to_cam)  and Pytorch3D. Here is the function that converts OpenCV -> Pytorch3d, `_cameras_from_opencv_projection()`:

https://github.com/fairinternal/pytorch3d/blob/b5ebc857c983867bc9fdc0d2f826cf87fa948d0c/pytorch3d/renderer/camera_conversions.py#L21

and here is the one that converts Pytorch3d -> OpenCV, `_opencv_from_cameras_projection()`:


https://github.com/fairinternal/pytorch3d/blob/b5ebc857c983867bc9fdc0d2f826cf87fa948d0c/pytorch3d/renderer/camera_conversions.py#L64
