### ISSUE TITLE
Some problem about the demo.py

### ISSUE THREAD

**Issue by SakuBorder** [facebookresearch/PoseDiffusion#22]
Hello, when running your demo.py, there is a problem "cannot import name 'compute_ARE' from 'util.metric'", I checked the file util/metric.py, but found that there is no function named compute_ARE , maybe this function you mean is actually the "camera_to_rel_deg" ?
![image](https://github.com/facebookresearch/PoseDiffusion/assets/44521782/dff9f8fe-1030-450e-b9c7-0eafbce72f27)

**Comment by SakuBorder** [comment]
> And in line 52, "images, image_info = load_and_preprocess_images(folder_path, cfg.image_size)", I believe that "cfg.image_size" is an integer and cannot be sorted. Perhaps it can be written as "images, image_info = load_and_preprocess_images(folder_path)"?

Or need to specify the corresponding parameters?

**Comment by jytime** [comment]
Hi,

Yes you are right.  Apologize I have not updated the demo.py file after updating the utility function. The current demo.py was the one used in previous versions.```compute_ARE``` was previous metric function, and can be found in [this commit](https://github.com/facebookresearch/PoseDiffusion/blob/34080949228513a229c32df7bda4e965031b367f/pose_diffusion/util/metric.py) 

The current ```load_and_preprocess_images``` function, expects either of ```folder_path```  or ```image_paths``` to be not None. You can call it as load_and_preprocess_images(folder_path = folder_path, image_paths = None, image_size= cfg.image_size).

**Comment by SakuBorder** [comment]
> Hi,
> 
> Yes you are right. Apologize I have not updated the demo.py file after updating the utility function. The current demo.py was the one used in previous versions.`compute_ARE` was previous metric function, and can be found in [this commit](https://github.com/facebookresearch/PoseDiffusion/blob/34080949228513a229c32df7bda4e965031b367f/pose_diffusion/util/metric.py)
> 
> The current `load_and_preprocess_images` function, expects either of `folder_path` or `image_paths` to be not None. You can call it as load_and_preprocess_images(folder_path = folder_path, image_paths = None, image_size= cfg.image_size).

Thank you for your response. I've also identified some similar issues. For example, should the 51st line of `demo.py` return three parameters: `images`, `image_info`, and `image_paths`? Should corresponding modifications be made to the `load_img_folder.py` function? Additionally, should the input parameters of the `extract_match` function in the 79th line include the `image_paths` parameter that was returned earlier?

**Comment by gleize** [comment]
https://github.com/facebookresearch/PoseDiffusion/pull/23 should fix that.

**Comment by jytime** [comment]
Thank you @gleize !

**Comment by SakuBorder** [comment]
Thanks!
