### ISSUE TITLE
Relative rotation estimation

### ISSUE THREAD

**Issue by sailor-z** [facebookresearch/PoseDiffusion#28]
Hi,

Thanks for releasing the code of this amazing work. I'm a little confused about why the relative rotation from i-th to j-th camera is estimated as $R_iR_j^{T}$. I thought it would be $R_jR_i^{T}$.

**Comment by jytime** [comment]
Hi,

This aims to be consistent with the pytorch3d package. While, as long as you use the same for the gt and prediction, it will not make a difference by using RiRjT or RjRiT.

Best,
Jianyuan
