### ISSUE TITLE
About the guidance gradient during the reversing process

### ISSUE THREAD

**Issue by songlin** [facebookresearch/PoseDiffusion#31]
Hello, 
Thanks for the great work and sharing the code.  I have a question related to the gradient $\nabla_{x_t}logp(I|x_t)$, which appears in the Fig.3 and Eqn 8. From the text of the paper, this gradient should be *added* to the predicted mean during reversing process. However, from the code, it seems *replaces* the predicted mean $\mu$.

https://github.com/facebookresearch/PoseDiffusion/blob/1664194a2e9b021f38459aa0bd1b49b8f5045fa4/pose_diffusion/models/gaussian_diffuser.py#L266-L280

Can you elaborate more? 
Thank you.

**Comment by jytime** [comment]
Hi Songlin,

Thanks for your interest. The detailed implementation of GGS (Eq. 8) can be found [here](https://github.com/facebookresearch/PoseDiffusion/blob/1664194a2e9b021f38459aa0bd1b49b8f5045fa4/pose_diffusion/util/geometry_guided_sampling.py#L67), which corresponds to `cond_fn` of the code shared above. We can see that we gradually optimize `model_mean` (which is the camera parameter vector) to approach a geometery consistent solution. Each optimization step will slightly change `model_mean`, and can be viewed as adding a residual there. Hope this can solve your question.

Best,
Jianyuan

**Comment by songlin** [comment]
Hi Jianyuan,

Thank you for the kind explanation which make perfectly sense to me.
