### ISSUE TITLE
Number of Image Pairs in computing Sampson Epipolar Error

### ISSUE THREAD

**Issue by Arjeus** [facebookresearch/PoseDiffusion#32]
Hi,

I would like to clarify how how may image pairs are computed for their respective Sampson Epipolar Error. Are all combinations used? Or just a subset of it? Thanks.

**Comment by jytime** [comment]
Hi Arjeus,

yes, for one scene, all the pairs are used.

(please note that some matches are filtered out if they do not satisfy the https://github.com/facebookresearch/PoseDiffusion/blob/57d644416cd31038c5dacc883b9136e2a609f029/pose_diffusion/util/geometry_guided_sampling.py#L170)
