### ISSUE TITLE
Please Provide Some Advice on Sparse Viewpoint Reconstruction

### ISSUE THREAD

**Issue by kke19** [facebookresearch/PoseDiffusion#38]
HI, I am very grateful for your research and how it has helped my work. However, I have encountered a problem. I hope to generate sparse point clouds using the results produced by your research. In the past, I have used COLMAP to generate sparse point clouds, but now my research scenario has changed to sparse point cloud reconstruction under sparse viewpoints, and COLMAP has failed in this scenario.
﻿
If you know how to reconstruct sparse point clouds using the sparse viewpoints poses produced by your research, please provide me with some guidance. Thank you very much.

**Comment by jytime** [comment]
Hi,

Have you checked https://github.com/facebookresearch/vggsfm ? It is a follow-up work to posediffusion. It should work well when the frame number is about 5-50, and will provide you with a 3D point cloud.
