### ISSUE TITLE
Generating visualizations code

### ISSUE THREAD

**Issue by jubelsM** [facebookresearch/PoseDiffusion#4]
Hi,
Is it possible to add the code that generates the visualizations on the project page?

**Comment by jubelsM** [comment]
Hi @jytime ,
Thanks for the quick response.
I have another question 😅, Is there any chance you'll release the training code?
I want to check your with a slightly more complicated camera model on a dataset I have.

**Comment by jytime** [comment]
Hi @jubelsM ,

Yes! We hope we can share the training code in late July :)

**Comment by jytime** [comment]
Hi @jubelsM , please note that I updated the dev branch for training script just now. This is slightly different from the dev branch last week. It should be able to reproduce the training result now. 

I will clean the code and provide further instructions then.

**Comment by leo-frank** [comment]
Hi, 

> Hi @jubelsM ,
> 
> I will double check if we can share the visualisation code because it was based on an internal repository.

Is it allowed to share it ? I really love the visualisation style, LOL...

**Comment by umiskky** [comment]
> Hi,
> 
> > Hi @jubelsM ,
> > I will double check if we can share the visualisation code because it was based on an internal repository.
> 
> Is it allowed to share it ? I really love the visualisation style, LOL...

Any updates? Can you still share it? This visualization is really beautiful.

**Comment by jytime** [comment]
Hey the response I got is no we cannot share it publicly.
