### ISSUE TITLE
Thank you for providing such an excellent project, I would like to ask if it is possible to test it with my own dataset

### ISSUE THREAD

**Issue by wahiahia** [facebookresearch/PoseDiffusion#5]

**Comment by wahiahia** [comment]
This means that there are any requirements for image size or sharpness, resolution, etc.?

**Comment by jytime** [comment]
Hi @wahiahia ,

Sure, you can run the model on your own dataset following the practice as in [load_img_folder.py](https://github.com/facebookresearch/PoseDiffusion/blob/6ae78803c0d38a762fb4f08470111dda10264401/pose_diffusion/util/load_img_folder.py#L27)

One aspect you should pay attention to is the camera distribution. The presently released Co3D model was trained using the Co3D v2 dataset, where the cameras are usually positioned in a fly-around arrangement. The model can still work in alternative scenarios like fly-through, but you might notice a performance drop.

Please feel free to let me know if you meet any problem when using the model. We will also release the code of fine-tuning so you can train it on your own data then.

**Comment by wahiahia** [comment]
Thanks for your reply, I'm trying to restore the head camera pose, I took it works great between adjacent images but if the picture spans a little bit it doesn't work so well, I wonder if it's my head picture The extracted sift key points are not enough

**Comment by jytime** [comment]
Hi @wahiahia ,

I guess the number of keypoints may not be very important, while, you may get a better result with hloc instead of sift. And, to understand the situation better, could you describe what does "picture spans a little bit" mean?

**Comment by wahiahia** [comment]
What I mean is the time span, that is, when I have a device to acquire, maybe the first frame and the second frame, the third frame will match better, but when I rotate and translate, the first frame and the later frame registration is not very good.

**Comment by jytime** [comment]
Hi @wahiahia ,

Considering that the model is trained on Co3D, which does not incorporate extreme camera positions, its performance might degrade if the camera is excessively shifted upwards or downwards, or the new frames have little overlap with the others.
