### ISSUE TITLE
About camera pose result application

### ISSUE THREAD

**Issue by YuyanHuang** [facebookresearch/PoseDiffusion#7]
Hi,

Can I put the camera rotation and translation information calculated by your method directly into RC (RealityCapture) to reconstruct some weak texture situations where RC cannot be accurately aligned? Can the predicted camera pose result be directly used by RC？

Thanks!

**Comment by jytime** [comment]
Hi @YuyanHuang,

I think you can easily do this but may need to be careful about the system coordinate, for example, there are some discussion like [this](https://forums.unrealengine.com/t/camera-coordinate-system-explanation/712595/2).  The output cameras of PoseDiffusion follow the system coordinate as [here](https://pytorch3d.org/docs/cameras), where "+X points left, and +Y points up and +Z points out from the image plane". You should be able to set this in RealityCapture.

Best,
Jianyuan
