### ISSUE TITLE
Sampson Error / Guidance Question

### ISSUE THREAD

**Issue by crockwell** [facebookresearch/PoseDiffusion#8]
Hi Jianyuan Wang, 

Thanks for your great work! I had a couple questions about how Sampson Error / Guidance is implemented. It seems from the paper and demo code Sampson Guidance is implemented using SuperPoint+SuperGlue. 

(1) Is this also what is used for Sampson Error during training?
(2) How many frames are used to obtain Sampson Error and Sampson Guidance? I notice in the demo Sampson Guidance appears to use 20 frames for a 20 frame denoising example. For e.g. 3 frame denoising example, would SuperPoint+SuperGlue have 3 frames as input during inference? Training? I'd imagine it could be very tricky to extract correspondences with such a wide-baseline set.

Thanks so much!
Chris

**Comment by jytime** [comment]
Hi Chris,

Thanks for your interest. In PoseDiffusion, Sampson Error was only used for inference/sampling, and not used during training. The training process is just a typical diffusion process.

The number of frames used for SP&SG is exactly the same as used for the diffusion model. For the super-sparse setting, as you mentioned such as 3 frames, SP&SG only have 3 frames as input. In this case,
(1) if SP&SG cannot provide any valid matches, we would skip GGS, as shown [here](https://github.com/facebookresearch/PoseDiffusion/blob/34080949228513a229c32df7bda4e965031b367f/pose_diffusion/demo.py#L78). So it simply degenerates to a normal sampling, i.e., the same as "w/o GGS" in our paper. (2) if SP&SG can still provide some matches (we know they are noisy in this case), we will use the camera poses predicted by our diffusion model as a filter. This is done by filtering out the pairs that have a large sampson error. The code can be found [here](https://github.com/facebookresearch/PoseDiffusion/blob/34080949228513a229c32df7bda4e965031b367f/pose_diffusion/util/geometry_guided_sampling.py#L213C36-L213C36), that any pair of match would be removed if its corresponding sampson error is higher than a hyperparameter "sampson_max".


Please feel

**Comment by crockwell** [comment]
Oh cool, I really like that strategy! Thanks for explaining, this makes things super clear :)
